In [3]:
%pip install numpy

     ---------------------------------------- 0.0/14.8 MB ? eta -:--:--
     ---------------------------------------- 0.2/14.8 MB 3.1 MB/s eta 0:00:05
      --------------------------------------- 0.4/14.8 MB 3.7 MB/s eta 0:00:04
     -- ------------------------------------- 1.0/14.8 MB 6.0 MB/s eta 0:00:03
     --- ------------------------------------ 1.4/14.8 MB 5.9 MB/s eta 0:00:03
     ---- ----------------------------------- 1.8/14.8 MB 5.8 MB/s eta 0:00:03
     ----- ---------------------------------- 2.1/14.8 MB 5.6 MB/s eta 0:00:03
     ------ --------------------------------- 2.3/14.8 MB 5.5 MB/s eta 0:00:03
     ------ --------------------------------- 2.6/14.8 MB 5.1 MB/s eta 0:00:03
     ------- -------------------------------- 2.9/14.8 MB 5.0 MB/s eta 0:00:03
     -------- ------------------------------- 3.2/14.8 MB 4.9 MB/s eta 0:00:03
     --------- ------------------------------ 3.4/14.8 MB 4.7 MB/s eta 0:00:03
     --------- ------------------------------ 3.6/14.8 MB 4

In [2]:
import numpy as np
lst = [3,54,6,7,8]
print(lst,type(lst))
arr=np.array(lst)
print(arr,type(arr))

[3, 54, 6, 7, 8] <class 'list'>
[ 3 54  6  7  8] <class 'numpy.ndarray'>


In [3]:
print(arr.size)

5


In [7]:
print(arr.shape,arr.ndim)

(5,) 1


In [9]:
np.arange(0,15,3)

array([ 0,  3,  6,  9, 12])

In [10]:
np.linspace(0,1,9)

array([0.   , 0.125, 0.25 , 0.375, 0.5  , 0.625, 0.75 , 0.875, 1.   ])

In [11]:
np.linspace(10,100,10,dtype=float)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

# Random

In [13]:
np.random.rand(3,2)

array([[0.97687408, 0.16098466],
       [0.7268007 , 0.88790619],
       [0.2450994 , 0.10717205]])

# Infer